<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP1Ue5oG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP1Ue5oG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP1Ue5oG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP1Ue5oG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerP1Ue5oG\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'P1Ue5oG',
    'container.build_id' => 'b2e1166d',
    'container.build_time' => 1544280868,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerP1Ue5oG');
