<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU74a4qp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU74a4qp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU74a4qp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU74a4qp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU74a4qp\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'U74a4qp',
    'container.build_id' => '1ad5361a',
    'container.build_time' => 1543863158,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerU74a4qp');
